@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "victor.training.cleancode.fp.PureFunction",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1276119258 { 
   	label=training
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_27700130 { 
   	label=cleancode
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   Coupon996133904[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Coupon</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   autoApply: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   category: ProductCategory [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   discountAmount: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ apply(product: Product, price: Double): Double</TD></TR>
<TR><TD ALIGN="LEFT" >+ autoApply(): boolean</TD></TR>
<TR><TD ALIGN="LEFT" ># canEqual(other: Object): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ isApplicableFor(product: Product): boolean</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Customer996133904[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Customer</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   coupons: List&lt;Coupon&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ coupons(): List&lt;Coupon&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

PureFunction1125000401[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)PureFunction</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   couponRepo: CouponRepo [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   customerRepo: CustomerRepo [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   productRepo: ProductRepo [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   thirdPartyPricesApi: ThirdPartyPricesApi [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ computePrices(customerId: long, productIds: List&lt;Long&gt;, internalPrices: Map&lt;Long, Double&gt;): Map&lt;Long, Double&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
Customer996133904 -> Coupon996133904[label="coupons
[0..*]"];
PureFunction1125000401 -> Customer996133904[label="computePrices() -> coupons()"];
    
}
@enduml