package victor.training;

public enum MechanicType {
SURPRISE,

   DISCOUNT, PROMOTION_PRICE, MULTI_UNIT_SIMQTY_LOWEST_PRICE, MULTI_UNIT_SIMQTY_HIGHEST_PRICE, MULTI_UNIT_FIXED_COMBINATION, MULTI_UNIT_VARIO_COMBINATION, MULTI_UNIT_POOL_COMBINATION, MULTI_UNIT_LAYERED_COMBINATION, MULTI_UNIT_PACK_AND_COMBO, NON_VALUE_NO_DISCOUNT, NON_VALUE_SMALL, NON_VALUE_MEDIUM, NON_VALUE_LARGE, MULTI_UNIT_SIMQTY_EVERY_ITEM
}
